all: cptime fchmod ftype link list1 list2 rlink touch unlink

cptime: cptime.c
	gcc -o cptime cptime.c

fchmod: fchmod.c
	gcc -o fchmod fchmod.c

ftype: ftype.c
	gcc -o ftype ftype.c

link: link.c
	gcc -o link link.c

list1: list1.c
	gcc -o list1 list1.c

list2: list2.c
	gcc -o list2 list2.c

rlink: rlink.c
	gcc -o rlink rlink.c

touch: touch.c
	gcc -o touch touch.c

unlink: unlink.c
	gcc -o unlink unlink.c